name: Generate Docs
on: [push]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create docs
        uses: mattnotmitt/doxygen-action@v1.9.5
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html/
          allow_empty_commit: false
          publish_branch: gh-pages
          destination_dir: docs
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
